### ISSUE TITLE
What is the point of uploading something which does not work. is it just show off

### ISSUE THREAD

**Issue by hammad2224** [atiksoftware/pubg_mobile_memory_hacking_examples#13]
Hi Man,

What is the point of uploading something which does not work?
i tried your modified reclass.net it simply does not work.
you have shown no information how and where to start with it

Is it just a showoff thread where you show who has the bigger dick

Useless information if it does not work. or if it has no documentation how to make it work

**Comment by mazid12345** [comment]
[> Hi Man,_
> 
> 
> 
> What is the point of uploading something which does not work?
> 
> i tried your modified reclass.net it simply does not work.
> 
> you have shown no information how and where to start with it
> 
> 
> 
> Is it just a showoff thread where you show who has the bigger dick
> 
> 
> 
> Useless information if it does not work. or if it has no documentation how to make it work

]([]())

**Comment by atiksoftware** [comment]
@hammad2224 
First of all, I try to help everyone who asks a polite question as much as I can.
if you read README.md files, you can understands why i update thats.
İ just sharing my some experiences to community.
if you are experienced in software you can know how can you use this. so many person using it correctly

i shared reclass source code on there ([ReClass.NET.zip](https://github.com/atiksoftware/pubg_mobile_memory_hacking_examples/blob/master/ReClassModified/ReClass.NET.zip)). 
you need just edit source project for your target application.
you can look to [ReadRemoteMemory.cpp](https://github.com/atiksoftware/pubg_mobile_memory_hacking_examples/blob/master/ReClassModified/NativeCore/Windows/ReadRemoteMemory.cpp) file for what should edit.

in addition its not about show who has the bigger dick.
i am sad because of learned that you are interest to bigger dick.
